---
- name: Creating network
  # ignore_errors: true
  community.docker.docker_network:
    name: "{{ network_name }}"
    driver: overlay

- name: Service deploy
  include: "../services/{{ item.name }}/service.yml"
  vars:
    - name: "{{ item.name }}"
    - version: "{{ item.version }}"
  loop: "{{ services }}"