---
- name: user
  hosts: demo
  tasks:
    - name: Preconfig block
      block:
        - name: Sleep
          command: /bin/sleep 15
          async: 1000
          poll: 5
          register: sleep
        - name: Echo
          command: echo "Done"
      become: true
      - name: Check sleep status
        async_status:
          jid: "{{ sleep.ansible_job_id}}"
    

      
 

