galaxy_info:
  role_name: swarm_join
  description: Connect to swarm cluster
  company: your company (optional)
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all