- name: "[{{ name }}] Configure secret"
  block:
    - name: "[{{ name }}] Create secret"
      include: "secret-create.yml"
  tags: "{{ name }}"

  rescue:
    - name: "[{{ name }}] Delete service"
      community.docker.docker_secret:
        name: "{{ name }}"
        state: absent
  
    - name: "[{{ name }}] Create secret"
      include: "secret-create.yml"